services:
  frontend:
    build: frontend/
    ports:
      - "80:5173"
    depends_on: [backend]

  backend:
    build: backend/
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    depends_on:
      neo4j:
        condition: service_started
      chromadb:
        condition: service_started
    volumes:
      - ./backend/migrations:/home/myuser/migrations

  neo4j:
    image: neo4j:2026.05.0
    env_file:
      - backend/.env
    ports:
      - "6868:7474"
      - "6969:7687"
    volumes:
      - neo4j:/etc/neo4j

  chromadb:
    image: chromadb/chroma
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  neo4j:
  chromadb:
  postgres_data:
