services:
  frontend:
    build: frontend/
    ports:
      - "8080:8080"
    depends_on: [api]

  api:
    build: api/
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      # neo4j:
      #   condition: service_started
      # chromadb:
      #   condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./api/migrations:/home/myuser/migrations

  coref:
    build: coref/
    ports:
      - "5001:5001"
    env_file:
      - ./.env

  neo4j:
    image: neo4j:2026.05.0
    env_file:
      - ./.env
    ports:
      - "6868:7474"
      - "6969:7687"
    volumes:
      - neo4j:/etc/neo4j

  chromadb:
    image: chromadb/chroma
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - chromadb:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma

  postgres:
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  neo4j:
  chromadb:
  postgres_data:
